<?php
// +----------------------------------------------------------------------
// |Description: 								     
// +----------------------------------------------------------------------
// |Company：西安一笔一画科技有限公司     					   	 
// +----------------------------------------------------------------------
// |Author：Delbert <18629435343@163.com>  	  
// +----------------------------------------------------------------------
// |CreatTime:2018/7/10 14:08 	  
// +----------------------------------------------------------------------

namespace app\index\controller;


use think\Request;

class Ask extends Main
{
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
    }


    /**
     * 父类方法重载
     */
    public function getInfo()
    {

        parent::getInfo(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //分页获取问答列表
        $db = db('ask')
            ->where('is_show',1)
            ->order('sort,id desc');
        $asks = parent::_page($db,5);
        $this->assign([
            'asks'  => $asks
        ]);
        return $this->fetch();
    }

    public function show($id = 0)
    {
        //详情
        $ask = db('ask')
            ->where('is_show',1)
            ->where('id',$id)
            ->limit(1)
            ->find();
        $this->assign([
            'ask' => $ask
        ]);
        return $this->fetch();
    }
}