<?php
namespace app\index\controller;

use think\Request;

class Index extends Main
{
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
    }

    /**
     * 父类方法重载
     */
    public function getInfo()
    {

        parent::getInfo(); // TODO: Change the autogenerated stub
        $this->title = 'index';
    }

    /**
     * 官网首页
     * @return mixed
     */
    public function index()
    {
        //获取轮播图
        $banner = parent::getBanner();
        //获取产品
        $product = db('pro')
            ->where('is_show',1)
            ->order('sort,id')
            ->limit(10)
            ->field('id,name,abs,thumb,title,alt')
            ->select();
        //获取客户评价
        $say = db('pj')
            ->where('is_show',1)
            ->order('sort,id')
            ->limit(5)
            ->field('id,name,content,thumb,title,alt')
            ->select();
        //获取新闻
        //1.获取第一条新闻
        $fNew = db('news')
            ->order('sort desc,id desc')
            ->find();
        $bNew = db('news')
            ->order('sort desc,id desc')
            ->where('id','neq',$fNew['id'])
            ->find();
        $listNews = db('news')
            ->whereNotIn('id',[$fNew['id'],$bNew['id']])
            ->order('sort desc,id desc')
            ->limit(2)
            ->select();
        $this->assign([
            'banner' => $banner,
            'product'=> $product,
            'say'    => $say,
            'fNew'   => $fNew,
            'bNew'   => $bNew,
            'listNews'=> $listNews,
        ]);
        return $this->fetch();
    }


}
