<?php
// +----------------------------------------------------------------------
// |Description: 								     
// +----------------------------------------------------------------------
// |Company：西安一笔一画科技有限公司     					   	 
// +----------------------------------------------------------------------
// |Author：Delbert <18629435343@163.com>  	  
// +----------------------------------------------------------------------
// |CreatTime:2018/6/14 16:13 	  
// +----------------------------------------------------------------------

namespace app\index\controller;


use think\Db;
use think\Request;

class News extends Main
{

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
    }

    /**
     * 父类方法重载
     */
    public function getInfo()
    {

        parent::getInfo(); // TODO: Change the autogenerated stub
    }

    /**
     * 新闻列表页
     * @param int $cid
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function index($cid = 0)
    {
        if($cid == 0)
        {
            $cid = db('news_cate')
                ->order('sort,id')
                ->limit(1)
                ->value('id');
        }
        //分页获取新闻列表
        $db = db('news')
            ->where('is_show',1)
            ->where('pid',$cid)
            ->order('sort,id desc')
            ->field('id,name,abs,uid,addtime,thumb,title,alt');
        $news = parent::_page($db,5);
        //获取新闻分类
        $cateInfo = db('news_cate')
            ->order('sort,id')
            ->select();

        $this->assign([
            'cateInfo'  => $cateInfo,
            'news'      => $news,
            'cid'       => $cid,
        ]);
        return $this->fetch();
    }

    public function show($id = 0)
    {
        //获取新闻详细信息
        $new = db('news')
            ->alias('n')
            ->join('news_dtl nd','n.id=nd.news_id')
            ->where('is_show',1)
            ->where('n.id',$id)
            ->limit(1)
            ->find();
        //类别
        $pid = $new['pid'];
        //上一篇
        $lastId = db('news')
            ->where('pid',$pid)
            ->where('id','>',$id)
            ->order('id asc')
            ->limit(1)
            ->value('id');
        $lastNew = db('news')
            ->where('is_show',1)
            ->where('id',$lastId)
            ->limit(1)
            ->find();
        //下一篇
        $nextId = db('news')
            ->where('pid',$pid)
            ->where('id','<',$id)
            ->order('id desc')
            ->limit(1)
            ->value('id');
        $nextNew = db('news')
            ->where('is_show',1)
            ->where('id',$nextId)
            ->limit(1)
            ->find();

        //获取最新的新闻列表
        $nNews = db('news')
            ->where('is_show',1)
            ->where('pid',$pid)
            ->whereNotIn('id',$id)
            ->order('addtime desc,sort,id desc')
            ->limit(6)
            ->select();
        $this->assign([
            'new'   => $new,
            'lastNew' => $lastNew,
            'nextNew' => $nextNew,
            'nNews'    => $nNews
        ]);
        return $this->fetch();
    }

}